### PR TITLE
Update naming convention for Header and Navigation

### PR DESCRIPTION
**Pull request by Kaif987**

### CODE REVIEW

**Comment by Kaif987** [comment]
hey this is my first contribution to open source. so if I made any mistake I am open to suggestions.

**Comment by nikolap994** [comment]
Did you close the issue by mistake ?

**Comment by Kaif987** [comment]
Yes, I am sorry. I closed the PR by mistake.

**Comment by nikolap994** [comment]
This looks good, I will merge it 👍🏻

**Pull request merged**
