### PR TITLE
 Added Link to Status Page to Navigation #30 

### PR DESCRIPTION
**Pull request by ammarali0608**
issue #30 has been solved please consider and close it

### CODE REVIEW

**Comment by nikolap994** [comment]
Thank you @ammarali0608 , @cehicm can you do the review ?

**Review by cehicm — APPROVED** [review]
Great work, thanks!

**Comment by cehicm** [comment]
I approved the merge @ammarali0608 ! Could you clean up the menu styles in general, or should I open another Issue?

**Comment by ammarali0608** [comment]
I didn't get the meaning of cleaning up the styles in general. Please specify so I can tell you if I can do it. Thanks

**Comment by cehicm** [comment]
Screenshot_4
Screenshot_5

I meant to make the Nav look better, on smaller screens in particular. Perhaps make the Status nav item stand out somehow as well. Hope this clears it up.

**Comment by ammarali0608** [comment]
I got it , but please open an issue for this because I will try, but another can come up with a better solution there also

**Comment by cehicm** [comment]
Opened.

**Pull request merged**
