### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by maddy020**
Creating a PR for authentication 
Please help for solving this

### CODE REVIEW

**Comment by nikolap994** [comment]
I've created new branch and added changes for auth.
https://github.com/Evil-Bees/Alertit/commit/7fa511244d7023aeca37a6f3aa73dfefb6e28b53

We need to intercept google session and create user in our database that will be saved. 
The user is required because just session that is in browser is not resolving issue with creating new Monitors. 

You were missing the check for provider, with this you can make session.

**Comment by maddy020** [comment]
I have done the changes and it is running smoothly in my system 
In the env file I set the cient id and secret given by you because I don't think so my credentials works in your system
Please review and merge the issue

**Comment by nikolap994** [comment]
Do you have successful session when you login ? 
Can you create new monitors at Dashboard  page and use the app without crashing ?

**Comment by maddy020** [comment]
Just got an error while redirecting to dashboard page
error

**Comment by nikolap994** [comment]
The issue is that session is created but does not exist in database as a user. Can you add logic to create user and authenticate it as we do it for credentials approach ?

**Comment by nikolap994** [comment]
After review I will leave this on feature branch for now. This looks good, however there is a issue with our integration with user options. Google Auth creates new collection in Mongo Database named Accounts. This makes it impossible to update on-go with new options, since every new sign in creates new entry. I wrote to Next Auth support to provide us with Documentation how we can intercept login to create new Account for us that will be reusable for each sign up.

Thank you for you hard work, if you want to work on any other issue, feel free to write us up.

Best, Nikola :)

**Pull request merged**
