### PR TITLE
toast notification is added status page

### PR DESCRIPTION
**Pull request by canberkkoc1**
toast notification is added status page

### CODE REVIEW

**Review by cehicm — CHANGES_REQUESTED** [review]
Looks pretty good, can we make it so that the message is automatically closed in 5 seconds, and have an animation to show the user that it's closing?

**Comment by canberkkoc1** [comment]
Yes, good idea, I can do that.

**Comment by canberkkoc1** [comment]
I think a new alert component has been added to the status page. So I'm canceling the changes.

**Comment by nikolap994** [comment]
I merged it along with other changes yesterday. Regarding the 5 seconds part, did you add it ?

**Comment by canberkkoc1** [comment]
Yes, I added the 5 seconds part, but I didn't add the closing animation.

**Comment by nikolap994** [comment]
Can you do that in new PR, or should I open new issue ?

**Comment by canberkkoc1** [comment]
Yes, I can open new PR, but do I need to remove the toast part? `props.showAlert("Please enter valid ID");` are we going to use that?

**Comment by nikolap994** [comment]
@cehicm what do you think we should do here ?

**Comment by cehicm** [comment]
Sorry about the confusion, we can use the new Alert component from now on, and just add the messages as needed.

**Comment by canberkkoc1** [comment]
Then I remove the toast notification. We use `props.showAlert("Please enter valid ID");`. I only open PR for input. Is it true?

**Comment by cehicm** [comment]
Yes, and add the changes we discussed. Also please pull the latest changes and open a new pull request.

**Comment by canberkkoc1** [comment]
I opened a new PR 👍🏼

**Pull request closed without merging**
