### PR TITLE
Review nedded 

### PR DESCRIPTION
**Pull request by BairamovAllaz**
Hi, I started to working on the task. I've created a simple, very simple version. I believe it needs a lot of updates, but I would like to know that I am in the right direction. Let me know.

### CODE REVIEW

**Comment by nikolap994** [comment]
Hello, this looks really good.
Since Status page is made for public, can we move it outside of dashboard folder.
We could make some form of "Search page" where you can input Monitor ID.
Lets take for example Monitor with ID: 6394eb28c13422f6251fb68e

When you search it it would open page:
http://localhost:3000/status/6394eb28c13422f6251fb68e

And it will show status info for all visitors.

The idea of status page is to make it possible for website owners to add it to their page and when page or server is down to show our status page in iframe or similar technology where it will confirm that site is offline at a moment or it's client side issue.

**Comment by BairamovAllaz** [comment]
I changed route as you said to http../status/id.Now I will create a search page with input bar  in center, and it will allow you to search monitors by name and go to it by clicking search button and some styling would be great I believe:) And question should I check user authenticate, or it will be open for unauthenticated users?

**Comment by nikolap994** [comment]
There is no need for authentication. Anyone can access it as long as they know ID of the monitor 😄 

Thank you for the hard work so far 👍🏻

**Comment by BairamovAllaz** [comment]
Okay then I am creating search page. What should I use for search name or id?

**Comment by nikolap994** [comment]
Lets go with the ID. 
Lets make it possible to search on 
 http../status/
and when ID is entered redirect to
 http../status/id
where result for that monitor will show, or if monitor does not exist, redirect to 404.

**Comment by BairamovAllaz** [comment]
Hey. I've added search page, let me know if any update needed.

**Comment by nikolap994** [comment]
When you fix syntax error, code wise this looks really good, are you up to update styles to make it look good for PC and mobile or should I open new issue for that for someone else to take ?

**Comment by BairamovAllaz** [comment]
You better open another issue for styling. I'm not gonna lie I'm still trying to understand nextjs and tailwind. But I will try opened issue.

**Comment by nikolap994** [comment]
Will do, can you just fix the class issue and I will merge the PR ?

**Comment by BairamovAllaz** [comment]
Sure I can fix but could you plear clearify which class?

**Comment by nikolap994** [comment]
pages/status/index.js on line 31, it should write className, not class :)

**Comment by BairamovAllaz** [comment]
Sorry😅
It is done..

**Comment by nikolap994** [comment]
Merged, ty for the great job 👍🏻  :)

**Comment by BairamovAllaz** [comment]
I will try to learn nextJs more deeply to help your project:)

**Comment by nikolap994** [comment]
Good luck, feel free to join us any time you want. We also have discord so feel free to join us and ask any questions you'd like :)

**Pull request merged**
